### ISSUE TITLE
Link to file is not removed when deleted

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#11]
In the tabular data entry widget, the link to file is not removed when deleted.

Steps
---
- Open tabular data entry for a stage which has a data element of type file.
- Upload a file (works well).
- Delete the file again.
- The link to the file is still there. Should now have been removed. When clicked it gives an error.

![file](https://cloud.githubusercontent.com/assets/908206/17444936/ed279232-5b42-11e6-8369-461fdadce5c6.png)

**Comment by jijukjose** [comment]
This issue is fixed in the current trunk.

**Comment by abyot** [comment]
can you also check with 2.24?

**Comment by jijukjose** [comment]
The issue is fixed in 2.24 as well.
Verified here - https://play.dhis2.org/demo/dhis-web-tracker-capture/index.html#/dashboard?tei=zu3VznPnM1s&program=ur1Edk5Oe2n&ou=DiszpKrYNg8.

Fixed an issue that ec datastore is accessed instead of tc data store for restoring the system settings. 
git commit 2258166..1ab6d5f.

This issue is absent in the trunk.
